Update 通用设备编译固件.yml

diff --git a/.github/workflows/通用设备编译固件.yml b/.github/workflows/通用设备编译固件.yml
--- a/.github/workflows/通用设备编译固件.yml
+++ b/.github/workflows/通用设备编译固件.yml
@@ -19,7 +19,7 @@ on:
           - lede-master
           - immortalwrt-master
           - Lienol-master
-      
+
 env:
   FEEDS_CONF: config/${{ inputs.source_branch }}/feeds.conf.default
   CONFIG_FILE: config/${{ inputs.source_branch }}/config
@@ -44,6 +44,7 @@ jobs:
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
+          set -e  # Exit immediately if a command exits with a non-zero status
           docker rmi $(docker images -q) || true
           sudo rm -rf "${AGENT_TOOLSDIRECTORY}" /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null || true
           sudo -E apt-get -y update
@@ -61,7 +62,7 @@ jobs:
         working-directory: /workdir
         if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          # Set up compilation source code
+          set -e
           case "${{ inputs.source_branch }}" in
             *"openwrt"*) REPO_URL="https://github.com/openwrt/openwrt"; REPO_BRANCH="main"; TAGS_NAME="official";;
             *"lede"*) REPO_URL="https://github.com/coolsnowwolf/lede"; REPO_BRANCH="master"; TAGS_NAME="lede";;
@@ -70,12 +71,10 @@ jobs:
             *) echo "Unknown source code repository."; exit 1;;
           esac
 
-          # Clone source code
           git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
           ln -sf /workdir/openwrt ${GITHUB_WORKSPACE}/openwrt
 
-          # Set output information
-          echo "build_tag=OpenWrt_${TAGS_NAME}_${{ inputs.openwrt_storage }}_$(date +"%Y.%m")" >> $GITHUB_ENV
+          echo "build_tag=OpenWrt_${TAGS_NAME}_$(date +"%Y.%m")" >> $GITHUB_ENV
           echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nTAGS_NAME: [ ${TAGS_NAME} ]"
           df -hT ${PWD}
           echo "status=success" >> $GITHUB_ENV
@@ -115,7 +114,7 @@ jobs:
         run: |
           cd openwrt/
           echo -e "$(nproc) thread compile"
-          make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
+          make -j$(($(nproc) + 1)) V=s || (echo "Compile failed, attempting single-threaded compile..." && make -j1 V=s)
           echo "status=success" >> $GITHUB_ENV
 
       - name: Check space usage
